Friend Module Constants
    Friend Const ChangeHeadingText = "Change Heading..."
    Friend Const ChangeSpeedText = "Change Speed..."
    Friend Const ConfirmQuitTitle = "[red]Are you sure you want to quit?[/]"
    Friend Const FireTorpedoText = "Fire Torpedo..."
    Friend Const LoadTorpedoText = "Load Torpedo..."
    Friend Const MainMenuTitle = "[olive]Main Menu:[/]"
    Friend Const NeverMindText = "Never Mind"
    Friend Const NewGameText = "New Game"
    Friend Const NextTurnText = "Next Turn"
    Friend Const NoText = "No"
    Friend Const PewPewStarshipsTitle = "Pew Pew Starships!"
    Friend Const QuitText = "Quit"
    Friend Const ScanText = "Scan..."
    Friend Const YesText = "Yes"
End Module
